verbose = true
no-progress = true
scheme = []
base = "./public"
exclude-mail = true
include = ["./public/**/*.md", "./public/**/*.html"]
exclude = [
  "https://fonts.gstatic.com/",
  "https://fonts.googleapis.com/",
  "https://www.clarity.ms/tag/",
  "https://www.googletagmanager.com/gtm.js",
  ".*/mailto:.*@.*",
  "https://tea.xyz/tea.white-paper",
  "https://tea.xyz/tea.products",
  "https://tea.xyz/tea.nebraska-man",
  "https://tea.xyz/tea.cli",
  "https://github.com/teaxyz/pantry"
]
